/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Action: typeof import('./src/components/Action.vue')['default']
    Contact: typeof import('./src/components/Contact.vue')['default']
    Event: typeof import('./src/components/Event.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Formule: typeof import('./src/components/Formule.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Heroe: typeof import('./src/components/Heroe.vue')['default']
    Partenaire: typeof import('./src/components/Partenaire.vue')['default']
    PresStreetWorkout: typeof import('./src/components/PresStreetWorkout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollTopButton: typeof import('./src/components/ScrollTopButton.vue')['default']
    Stats: typeof import('./src/components/Stats.vue')['default']
    StreetWorkout: typeof import('./src/components/StreetWorkout.vue')['default']
    Vision: typeof import('./src/components/Vision.vue')['default']
  }
}
